
my-app:
  msg: Successfully scanned for virus and converted to PDF (Globaly-Shared among multiple service(s)!!!).
  list:
    values: one, two, three

app:
  description: ====== This is a spring config client. (Default global config - Globaly-Shared) =========

db:
  connection: conn-string-here
  host: 127.0.0.1
  port: 1200
